# Config file for set up of the deep learning framework

trainer:
  epochs:
    10

  universal_logger:
    name: 'Universal Logger'
    console: True

  model:
    model:
      d_in:
        3

  callback:
    data_loader:
      batch_size:
        2
      input_type:
        folder_path
      folders:
        - /Users/aria/Downloads/Nexus_Week23_Part2_A_2020_Completed/img
        - /Users/aria/Downloads/Nexus_Week23_Part2_A_2020_Completed/labels
      test_ratio:
        0
      val_ratio:
        .4
      shuffle:
        False

    process:
      preprocess:
        resize:
          destination_image_size: !!python/tuple [384, 512]

    test:
      - the_first
      - the_second:
          - this_has_surpise
          - this_too
      - the_third
      - the_fourth

    logger:
      tqdm:
        chert:
          5
        kolooche:
          6
      TheProgressBar:
        chert:
          5
        kolooche:
          6