from .panacea import Panacea, PanaceaLeaf
from typing import Dict, Any
import re


console_colors = {
    "set": {
        "bold": 1,
        "dim": 2,
        "underlined": 4,
        "blink": 5,
        "inverted": 7,
        "hidden": 8
    },
    "reset": {
        "all": 0,
        "bold": 21,
        "dim": 22,
        "underlined": 24,
        "blink": 25,
        "inverted": 27,
        "hidden": 28
    },
    "foreground": {
        "set_8_16": {
            "default": 39,
            "black": 30,
            "red": 31,
            "green": 32,
            "yellow": 33,
            "blue": 34,
            "magenta": 35,
            "cyan": 36,
            "light_gray": 37,
            "dark_gray": 90,
            "light_red": 91,
            "light_green": 92,
            "light_yellow": 93,
            "light_blue": 94,
            "light_magenta": 95,
            "light_cyan": 96,
            "white": 97
        },
        "set_88_256": {
            "_prefix": "38;5;",
            "black": 0,
            "maroon": 1,
            "green": 2,
            "olive": 3,
            "navy": 4,
            "purple": 5,
            "teal": 6,
            "silver": 7,
            "grey": 8,
            "red": 9,
            "lime": 10,
            "yellow": 11,
            "blue": 12,
            "fuchsia": 13,
            "aqua": 14,
            "white": 15,
            "grey0": 16,
            "navyblue": 17,
            "darkblue": 18,
            "blue3": 19,
            "blue4": 20,
            "blue1": 21,
            "darkgreen": 22,
            "deepskyblue7": 23,
            "deepskyblue6": 24,
            "deepskyblue5": 25,
            "dodgerblue3": 26,
            "dodgerblue2": 27,
            "green4": 28,
            "springgreen6": 29,
            "turquoise4": 30,
            "deepskyblue4": 31,
            "deepskyblue3": 32,
            "dodgerblue1": 33,
            "green3": 34,
            "springgreen5": 35,
            "darkcyan": 36,
            "lightseagreen": 37,
            "deepskyblue2": 38,
            "deepskyblue1": 39,
            "green2": 40,
            "springgreen4": 41,
            "springgreen3": 42,
            "cyan3": 43,
            "darkturquoise": 44,
            "turquoise2": 45,
            "green1": 46,
            "springgreen2": 47,
            "springgreen1": 48,
            "mediumspringgreen": 49,
            "cyan2": 50,
            "cyan1": 51,
            "darkred1": 52,
            "deeppink7": 53,
            "purple5": 54,
            "purple4": 55,
            "purple3": 56,
            "blueviolet": 57,
            "orange3": 58,
            "grey37": 59,
            "mediumpurple6": 60,
            "slateblue2": 61,
            "slateblue1": 62,
            "royalblue1": 63,
            "chartreuse5": 64,
            "darkseagreen8": 65,
            "paleturquoise4": 66,
            "steelblue4": 67,
            "steelblue3": 68,
            "cornflowerblue": 69,
            "chartreuse4": 70,
            "darkseagreen7": 71,
            "cadetblue1": 72,
            "cadetblue": 73,
            "skyblue3": 74,
            "steelblue1": 75,
            "chartreuse3": 76,
            "palegreen3": 77,
            "seagreen3": 78,
            "aquamarine2": 79,
            "mediumturquoise": 80,
            "steelblue": 81,
            "chartreuse2": 82,
            "seagreen2": 83,
            "seagreen1": 84,
            "seagreen": 85,
            "aquamarine1": 86,
            "darkslategray2": 87,
            "darkred": 88,
            "deeppink6": 89,
            "darkmagenta1": 90,
            "darkmagenta": 91,
            "darkviolet1": 92,
            "purple2": 93,
            "orange2": 94,
            "lightpink4": 95,
            "plum4": 96,
            "mediumpurple5": 97,
            "mediumpurple4": 98,
            "slateblue": 99,
            "yellow6": 100,
            "wheat4": 101,
            "grey53": 102,
            "lightslategrey": 103,
            "mediumpurple": 104,
            "lightslateblue": 105,
            "yellow5": 106,
            "darkolivegreen5": 107,
            "darkseagreen6": 108,
            "lightskyblue2": 109,
            "lightskyblue1": 110,
            "skyblue2": 111,
            "chartreuse1": 112,
            "darkolivegreen4": 113,
            "palegreen2": 114,
            "darkseagreen5": 115,
            "darkslategray3": 116,
            "skyblue1": 117,
            "chartreuse": 118,
            "lightgreen1": 119,
            "lightgreen": 120,
            "palegreen1": 121,
            "aquamarine": 122,
            "darkslategray1": 123,
            "red3": 124,
            "deeppink5": 125,
            "mediumvioletred": 126,
            "magenta6": 127,
            "darkviolet": 128,
            "purple1": 129,
            "darkorange2": 130,
            "indianred4": 131,
            "hotpink4": 132,
            "mediumorchid3": 133,
            "mediumorchid": 134,
            "mediumpurple3": 135,
            "darkgoldenrod": 136,
            "lightsalmon2": 137,
            "rosybrown": 138,
            "grey63": 139,
            "mediumpurple2": 140,
            "mediumpurple1": 141,
            "gold2": 142,
            "darkkhaki": 143,
            "navajowhite3": 144,
            "grey69": 145,
            "lightsteelblue3": 146,
            "lightsteelblue": 147,
            "yellow4": 148,
            "darkolivegreen3": 149,
            "darkseagreen4": 150,
            "darkseagreen3": 151,
            "lightcyan3": 152,
            "lightskyblue": 153,
            "greenyellow": 154,
            "darkolivegreen2": 155,
            "palegreen": 156,
            "darkseagreen2": 157,
            "darkseagreen1": 158,
            "paleturquoise1": 159,
            "red2": 160,
            "deeppink4": 161,
            "deeppink3": 162,
            "magenta5": 163,
            "magenta4": 164,
            "magenta3": 165,
            "darkorange1": 166,
            "indianred2": 167,
            "hotpink3": 168,
            "hotpink2": 169,
            "orchid": 170,
            "mediumorchid2": 171,
            "orange1": 172,
            "lightsalmon1": 173,
            "lightpink3": 174,
            "pink3": 175,
            "plum3": 176,
            "violet": 177,
            "gold1": 178,
            "lightgoldenrod5": 179,
            "tan": 180,
            "mistyrose3": 181,
            "thistle3": 182,
            "plum2": 183,
            "yellow3": 184,
            "khaki3": 185,
            "lightgoldenrod4": 186,
            "lightyellow3": 187,
            "grey84": 188,
            "lightsteelblue1": 189,
            "yellow2": 190,
            "darkolivegreen1": 191,
            "darkolivegreen": 192,
            "darkseagreen": 193,
            "honeydew2": 194,
            "lightcyan1": 195,
            "red1": 196,
            "deeppink2": 197,
            "deeppink1": 198,
            "deeppink": 199,
            "magenta1": 200,
            "magenta": 201,
            "orangered1": 202,
            "indianred1": 203,
            "indianred": 204,
            "hotpink1": 205,
            "hotpink": 206,
            "mediumorchid1": 207,
            "darkorange": 208,
            "salmon1": 209,
            "lightcoral": 210,
            "palevioletred1": 211,
            "orchid2": 212,
            "orchid1": 213,
            "orange": 214,
            "sandybrown": 215,
            "lightsalmon": 216,
            "lightpink1": 217,
            "pink1": 218,
            "plum1": 219,
            "gold3": 220,
            "lightgoldenrod3": 221,
            "lightgoldenrod2": 222,
            "navajowhite1": 223,
            "mistyrose1": 224,
            "thistle1": 225,
            "yellow1": 226,
            "lightgoldenrod1": 227,
            "khaki1": 228,
            "wheat1": 229,
            "cornsilk1": 230,
            "grey100": 231,
            "grey3": 232,
            "grey7": 233,
            "grey11": 234,
            "grey15": 235,
            "grey19": 236,
            "grey23": 237,
            "grey27": 238,
            "grey30": 239,
            "grey35": 240,
            "grey39": 241,
            "grey42": 242,
            "grey46": 243,
            "grey50": 244,
            "grey54": 245,
            "grey58": 246,
            "grey62": 247,
            "grey66": 248,
            "grey70": 249,
            "grey74": 250,
            "grey78": 251,
            "grey82": 252,
            "grey85": 253,
            "grey89": 254,
            "grey93": 255,
        }
    },
    "background": {
        "set_8_16": {
            "default": 49,
            "black": 40,
            "red": 41,
            "green": 42,
            "yellow": 43,
            "blue": 44,
            "magenta": 45,
            "cyan": 46,
            "light_gray": 47,
            "dark_gray": 100,
            "light_red": 101,
            "light_green": 102,
            "light_yellow": 103,
            "light_blue": 104,
            "light_magenta": 105,
            "light_cyan": 106,
            "white": 107
        }
    }
}


def console_color_modifier(console_colors_dict: Dict) -> Dict:
    """Function to add \033[ before nad m after all the entries in the console color input dictionary.

    Parameters
    ----------
    console_colors_dict : Dict
        The dictionary containing the console color data

    Returns
    -------
    A dictionary with the correct colors

    """

    def console_color_modifier_helper(value, prefix=''):
        """Helper function to create the dictionary"""

        if type(value) == dict:
            out = {}
            for key, item in value.items():
                prefix = value['_prefix'] if '_prefix' in value.keys() else ''
                out[key] = console_color_modifier_helper(item, prefix)
        else:
            out = f'\033[{prefix}{value}m'

        return out

    # Create the dictionary
    out_dict = console_color_modifier_helper(console_colors_dict)

    return out_dict


class ColorParser(Panacea):

    def __init__(self, config_dict):

        super().__init__(config_dict=config_dict, leaf_class=ColorParserLeaf)


class ColorParserLeaf(PanaceaLeaf):

    def _item_str_representation(self) -> str:

        return f'{self._value}This is some sample text\x1b[0m\n'


CONSOLE_COLORS_CONFIG = ColorParser(console_color_modifier(console_colors)).enable_debug_mode()

