# Config file for set up of the deep learning framework

trainer:
  epochs:
    10

  universal_logger:
    name: 'Universal Logger'
    console: True

  model:
    model:
      d_in:
        3

  callback:
    data_loader:
      batch_size:
        2
      input_type:
        folder_path
      folders:
        - /home/aria/Pictures/samplePictures/img
        - /home/aria/Pictures/samplePictures/labels
      test_ratio:
        0
      val_ratio:
        .4
      shuffle:
        False
      multithreading:
        True

    process:
      preprocess:
        resize:
          destination_image_size: !!python/tuple [512, 512]

    test:
      - the_first
      - the_second:
          - this_has_surpise
          - this_too
      - the_third
      - the_fourth

    logger:
#      tqdm:
#        chert:
#          5
#        kolooche:
#          6
      TheProgressBar:
        chert:
          5
        kolooche:
          6